### ISSUE TITLE
Automatically Refresh the Folder View as Patches are Downloaded (Or add a Refresh Button)

### ISSUE THREAD

**Issue by mindtonic** [meanmedianmoge/zoia_lib#107]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I need to restart the app in order for the folders view to display patches as I download them. I am interested in categorizing things (internal Librarian tags would be really cool!) but have to restart the app in order to do so.

**Describe the solution you'd like**
Either have the apps internal storage pick up newly downloaded patches or provide a "refresh" button which will review what's new since last refresh.

Also, internal tagging would be awesome!

**Describe alternatives you've considered**
Restarting the app works.

**Additional context**
Just a big THANK YOU!!!

**Comment by meanmedianmoge** [comment]
If you hit enter in the search bar (on the Folders tab), the list should refresh without needing a restart. This is also true of the Local Storage tab, after downloading/importing. If neither of those are working, please let me know and I will investigate.

Nevertheless, I’ll try and optimize it so that even the enter step isn’t needed, and it just fetches the patches automatically.

Could you elaborate a bit more about internal tags and what that might look like? Each patch and version history includes tags and categories, which can be searched as a way to filter your patch list. I’d be happy to include more, but just wanna be clear about what you mean.

**Comment by meanmedianmoge** [comment]
Auto-fetch has been implemented. Release is coming within the next couple of days.
