### ISSUE TITLE
Add an auto-update option directly in-app

### ISSUE THREAD

**Issue by john-breton** [meanmedianmoge/zoia_lib#122]
**Is your feature request related to a problem? Please describe.**
Users need to manually fetch a new version of the app and delete the previous distribution any time a new release is prepared. 

**Describe the solution you'd like**
It would be nice if users could update the app directly to eliminate this step altogether (and this may help to keep the userbase up as new and better releases are prepared)!

**Describe alternatives you've considered**
We keep it the way it is, relying on the Discord and Reddit updates as the main source of news for the librarian, which I fear may alienate users that are not a part of those communities in the future.

**Additional context**
There are many apps that make use of this functionality on GitHub that we may be able to take inspiration from, the immediate one I can think of is the Microsoft Powertools distribution ([repo link here](https://github.com/microsoft/PowerToys)), although mostly written in C# and C++ this at least proves it is possible, likely making use of the GitHub API to check for new releases against the local version number

**Comment by smithrobs** [comment]
If we want to keep it in the python realm, [pyupdater](http://www.pyupdater.org) (relatively simple) or [TUF])https://theupdateframework.io/) (relatively complicated) seem to be the leading candidates. Not sure about the xplat situation there but I'd assume/hope it's all a matter of providing the right manifests.

My only other 0.02 on this - since it wasn't explicitly mentioned - is don't **auto** update, but check for updates and prompt the user to acknowledge and apply the update if they'd like.

I'd be happy to help out with this if y'all would like!

**Comment by meanmedianmoge** [comment]
I took a closer look at pyupdater, and it seems more useful for the build process than what this ticket describes (a user-facing prompt for updating based on the latest version). I've found a pretty quick and easy base library solution for this, which should be ready to go for 1.3!

I'll create a separate ticket for the build process optimizations.
