### ISSUE TITLE
Inconsistent patch naming on Mac OS using Import All vs Click to import

### ISSUE THREAD

**Issue by markcrosbie** [meanmedianmoge/zoia_lib#39]
On Mac OS when I import a single patch from the SD card the name shows up in the 'Local Storage View' with the full patch name in the format nnn_patchname.

When I use Import All Patches the names are stripped and only some of the patchname is displayed (do underscores in patch names cause a problem?)

**Comment by john-breton** [comment]
Thanks for the report. 
The ### prefix, along with the _zoia_ prefix is supposed to be stripped when importing a patch; since they do not actually reflect the patch name and the Librarian takes care of adding those details back whenever something is exported.

So for example, if you try to import something with the name "009_zoia_patch.bin", it will be imported into the Librarian as just "patch", since that is the title of the patch.

I did find that if a patch is simply named "###_patch.bin" it incorrectly gets imported as "###_patch" and not just "patch", so this is the issue I will be correcting. 

If there is a reason for wanting the "###_zoia_" prefix to be retained when importing a patch I can change the functionality of the Librarian, but since those details are handled by the Librarian as it stands, I'm not sure why that would be desired.

**Comment by markcrosbie** [comment]
I think that might be the issue here, looking now some of the patches were missing the zoia_ part of the prefix in the name. Once I corrected that I think the importing is working ok

**Comment by john-breton** [comment]
Thank you for catching this.
In Beta 2, any numerical prefix or variations or "\_zoia\_" as a prefix will be stripped when importing, leaving only the patch name. There should no longer be any inconsistencies when importing a patch that lacks the "zoia\_" prefix either.
