### ISSUE TITLE
Utilizing the search bar resets column widths

### ISSUE THREAD

**Issue by Ch3ryl** [meanmedianmoge/zoia_lib#41]
**OS**: Windows 7 Professional Service Pack 1

When a user is using the search bar and hits enter or return to search, if they had adjusted the column widths within the respective view - those widths reset.

**Reproduction Steps**

1. Run the Zoia executable/ application
2. Navigate to any tab where the search bar is present - in this example, Patch Storage view
3. Adjust the width of the name column
4. Now Enter an empty search or a search term into the search bar - hit return/ enter
5. Observe the column widths reset

These steps are reproducible in PatchStorage, Local Storage Bank tab views

**Comment by john-breton** [comment]
Thanks for the catching this and the other table bug you reported earlier. I'll be sure to have them fixed in the next beta release!

**Comment by john-breton** [comment]
Due to the change with the application settings being saved and the code involved with that change, this bug no longer pops up (yay!). Thanks again for catching it. It shouldn't be an issue in the Beta 2 release. That being said, I'm sure there will be other UI/.UX bugs, so if you happen to find any I'll try my best to fix them.
