### ISSUE TITLE
Patch data missing if not downloaded from patch view

### ISSUE THREAD

**Issue by Ch3ryl** [meanmedianmoge/zoia_lib#45]
**OS:** Windows 7 Professional Service Pack 1

**Description**
When a user is utilizing Zoia librarian to organize patches they already downloaded manually, they will find details about that patch (except the file name) missing within the application. The user will only see details (tags, categories Author, Likes, Downloads, Views, License, Preview, and Patch Notes) if they downloaded the patch from Patch Storage view. Seems like there may need to be a way to sync files already downloaded with the info on patch storage?

**Reproduction Steps**

1. Have previously downloaded Zoia patches
2. Open the Zoia Librarian executable
3. Import the patches you downloaded in SD card view (after defining file path)
4. Now go to local storage and bank views - note those patches will only have their file names and no other info. You can compare this to a downloaded patch via the patch storage view.

![image](https://user-images.githubusercontent.com/50628195/88489276-69adda00-cf61-11ea-879a-d3dd0b916195.png)

**Notes**

Some quirks I noticed while investigating this issue:
- It's a little unintuitive that to sort for each view you have to click into the "Sort" menu item each time. It may make more intuitive sense for each view to have its own sort or clicking the column header would define the sorting pattern.
- It is a bit odd to not define the local storage view, it would be nice if I can pick where in my system this gets stored.

**Comment by meanmedianmoge** [comment]
I think this behavior is intentional, since patches downloaded from the Patchstorage website immediately lose all their metadata and you're left with the binary (or a zip directory with some patch files inside). Right now, the best way to retain the patch info is to use the "Update Patch Notes" functionality in the Local tab, copying over the PS notes of the same patch over. We may be able to come up with better ways to "merge" these similar data-points without requiring that copy step. I agree about the sorting - we have some improved sorting functionality planned.  

Hard-coded backend paths:
Windows: /APPDATA/.ZoiaLibraryApp
Mac: /Library/Application Support/.ZoiaLibraryApp
Linux: /.local/share/.ZoiaLibraryApp

We'll investigate if it makes sense to allow custom pathing. The data is masked a bit (using unique identifiers and JSON formats), so it's a bit confusing if you don't know what you're doing. The intention was to maintain the behavior of app storage for each OS. Happy to explain more!

**Comment by Ch3ryl** [comment]
Oh, I didn't see the update patch notes function - I will look again. I still have to post the issue with UX suggestions. But the explanation for how the paths are set up makes sense. But yeah, I may end up submitting "issues" that are not issues because I don't have purview in the development - sorry about that lol.

**Comment by john-breton** [comment]
> Oh, I didn't see the update patch notes function - I will look again. I still have to post the issue with UX suggestions. But the explanation for how the paths are set up makes sense. But yeah, I may end up submitting "issues" that are not issues because I don't have purview in the development - sorry about that lol.

No need to be sorry! Any feedback is greatly appreciated :)

**Comment by john-breton** [comment]
I have added a very rudimentary addition that will check to see if the patch being imported shares its title with a patch on PatchStorage. If this is true, then the metadata from PS will be used for the imported patch (which includes the patch notes, author, tags, categories, etc). This is something I may expand in a Beta 3 release, but hopefully, this helps for now
