### ISSUE TITLE
Mac pre-release is missing application

### ISSUE THREAD

**Issue by loop23** [meanmedianmoge/zoia_lib#59]
**Describe the bug**
Mac pre-release is missing .app

**To Reproduce**
1. Unzip ZOIA.Librarian.-.Beta.2.zip

**Expected behavior**
I except to find a .app folder/thing, and I don't

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
Further, could you please explain how to launch the app directly from the source code (ie: not from a release, just pull master or some other branch)

**Comment by john-breton** [comment]
This is not a bug and is something we are aware of. 
Unfortunately, the creation of a macOS release for Beta 2 is encountering some problems. This is part of the reason why we have not made an announcement for Beta 2. Once a .app is made, we will upload it and make announcements as we did for the release of Beta 1. The text for the release will be updated to reflect this.

If you would like to run the app from the source, I'd recommend cloning either master (stable) or beta-3 (unstable). Then, navigate to the top level zoia_lib directory in your console and run the command: python -m zoia_lib.backend.startup

**Comment by meanmedianmoge** [comment]
### How to install from source (in the event that you wish to test out secret/new features in branches, or the release candidates do not work for one reason or another)

**NOTE THAT THIS IS A GUIDE FOR MAC ONLY**

Requirements:
- Python 3.7 or above, either
-- Pre-installed by Apple, OR
-- Python.org https://www.python.org/downloads/release/python-379/, OR
-- Homebrew (https://brew.sh/ to install) https://docs.brew.sh/Homebrew-and-Python
- Local dependencies
-- Located in https://github.com/meanmedianmoge/zoia_lib/blob/master/requirements.txt
- Terminal
-- Open `/Applications/Utilities/Terminal`
- A version of the ZOIALibrarian source code, either
-- Downloaded straight from Github (click on the green "Code" button and press "Download ZIP".. then uncompress). This option is static in time and offers no version control, until you download a new version, OR
-- Pulled from Git (https://git-scm.com/ to install). This option is dynamic, lets you pull different branches of the code, and is a way to contribute to the project by submitting new features or bug fixes.
```
git clone https://github.com/meanmedianmoge/zoia_lib.git
git pull
OR
git checkout [feature-branch] # gets you super duper _new_ features, which may (definitely) have bugs in it..
```

Step-by step:
1) Download Python. Note that Mac machines (past a certain date of which I am not sure) do include minimal-working versions of Python 2.7 and 3.x. You'll need 3.7 or higher. To check which Python versions exist on your system
```
which -a python
python --version
python3 --version
```
If your python3 has version 3.7.x or higher, you're all set. If it does not, you can either install from the Python.org site or from Homebrew (this is the more "techy" option.. brew is a package manager that offers many useful solutions). If you choose to use brew, the commands required are:
```
# make sure you have brew https://brew.sh/
brew install python
```

2) Once Python 3.7.x is installed, double check you have the `pip3` module. pip is a Python package manager which you'll use to install dependencies so the application can run without errors. **Both methods of installing Python listed above should come with pip3.**
```
which -a pip3
pip3 --version
```

3) Install dependencies via pip. This will download various packages and set them in the appropriate paths so that Python is able to recognize and use them.
```
cd {location where you put the source code}
pip3 install -r requirements.txt
```

4) Now that you have Python and the necessary dependencies, the last step remaining is to start up the application. Executing the following should initialize the UI (you'll see the splash screen and eventually the full window). Please reach out if there are issues.
```
cd {location where you put the source code}
# to be specific, mine is cd Python/Projects/zoia_lib
python -m zoia_lib.backend.startup
```
