### ISSUE TITLE
Visualizer expansion window

### ISSUE THREAD

**Issue by chmjacques** [meanmedianmoge/zoia_lib#63]
It would be nice if, instead of having to resize everything to make the visualizer more accessible, you could perhaps double-click on the bar with the patch name and page above the visualizer and produce an expansion window for the visualizer.

**Describe alternatives you've considered**
Instead of an expansion window, perhaps being able to set a fixed re-sizing of the component windows for the visualizer.

**Additional context**

**Comment by meanmedianmoge** [comment]
As I've added more to the visualizer, I've been thinking about how to convey a quick set of information in addition to a very specific set. An expansion window is a solid idea.

Btw, just linking #62 here since they're somewhat related.

**Comment by eradicateiv** [comment]
Perhaps a more specific request, but I think taking a patch and providing a graphical representation of the modules, the pages, and most importantly, the connections between them would be awesome. I am thinking of something like MS SQL Studio that visualizes the database tables and foreign key links.

Very helpful to understand how things are working without having to tap around--also, the visualizer today does not give a unique ID to what specific instance of a module it is connected to.

**Comment by meanmedianmoge** [comment]
@eradicateiv this sort of thing is precisely what I had in mind!

As far as the current viz connection data, that’s a good point. We can point to the specific page and grid position to be more clear about which modules are actually connected. I’ll add that as a feature request (along with a couple other viz panel improvements).

**Comment by timgolden** [comment]
Is there a Python equivalent to R's DiagrammeR package?

**Comment by meanmedianmoge** [comment]
Update: attempting to utilize some portions of [this project](https://github.com/laurentgratton/zoia-explorer) for the expander view (`_calc_blocks` in patch_binary.py already pulled the code from here).

Proposed scenario is to add a button in the metadata/viz section of the LocalStorage tab which reads a given patch binary and opens a new window with the patch routing (including some options to minimize or highlight sections of the patch). If a full port/rewrite is required for the JS code, will utilize plotly instead.

**Comment by meanmedianmoge** [comment]
Some updates on this since the last check-in:

- Added a new button to the Local Storage viz panel to run the expanded visualization in a new window.

- This button originally used Pyvis network graphs, which was interesting but only offered a simple view of the patch, like so
<img width="555" alt="Screen Shot 2021-05-19 at 3 23 29 PM" src="https://user-images.githubusercontent.com/51132973/123808698-fc1bd380-d8be-11eb-9e70-4fbb9dec5e37.png">

- https://github.com/jchanvfx/NodeGraphQt is the best option I've been able to find so far. With NodeGraphQt, we can display complex routings in an abstract way and possibly then simplify down to the ZOIA grid (still need to develop a proof-of-concept for this step). This is a zoomed-in region of the Abyss Water patch, which still needs some additional work like colors, better organization of the modules, and font size. <img width="859" alt="Screen Shot 2021-06-29 at 9 50 12 AM" src="https://user-images.githubusercontent.com/51132973/123809196-6896d280-d8bf-11eb-96bf-5caf285d72d2.png">

- In developing this, I've noticed some changes to the ZOIA binary that I didn't expect. I reached out to Empress on what might have changed between 1.13 and 2.0 (now 2.1) to be sure. Solidifying this would be step one, as the patch expander relies on the decoding step.

**Comment by gregornoriskin** [comment]
Redirection from a Facebook thread: I cloned the nodegraph branch and ran the dependency update with packages listed in the text files. PIP resolves all of them except NodeGraphQT, telling me that it cannot find a package that meets the requirements. I am running 64-bit Python 3.9.x on Windows 10. Do I need a specific bitness and version of Python for HodeGraphQT?

**Comment by meanmedianmoge** [comment]
@gregornoriskin You need to clone the NodeGraphQt repo and use its setup.py for the dependency since it’s not on PIP yet (and still <1.0.0). Will update the requirements doc to reflect this.

**Comment by gregornoriskin** [comment]
> @gregornoriskin You need to clone the NodeGraphQt repo and use its setup.py for the dependency since it’s not on PIP yet (and still <1.0.0). Will update the requirements doc to reflect this.

Excellent. Thanks. This is a killer feature. I think everyone battles with understanding other people's patches and this is going to make it MUCH easier.

**Comment by gregornoriskin** [comment]
Got it running. It is already super helpful, even without being able to see the position of the modules on the grid. I really do think this is going to be a HUGE value add for folks attempting to understand and use other people's patches.

**Comment by gregornoriskin** [comment]
You should just ship it as is! I just took a complex patch and did a deep dive using the expanded view. Even without all the bells and whistles it is a very useful way to see the patch.

**Comment by meanmedianmoge** [comment]
Thanks for giving it a test run! I have a couple minor things to add and test before it's ready to ship, but that is promising and great to hear.

**Comment by meanmedianmoge** [comment]
This has been implemented and will be released soon in the version 1.2 release.
