### ISSUE TITLE
Allow for PS-Local merging to happen on non-identical patch names

### ISSUE THREAD

**Issue by Ch3ryl** [meanmedianmoge/zoia_lib#68]
**Describe the bug**

Within the local storage view, the update patch button does not do anything for patches where I have no patch note information. These patches were already in the local storage and not downloaded via Zoia Librarian.

**To Reproduce**

1. Ensure you have new patches in your local storage that were not downloaded via the librarian app
2. Within Zoialibrairan click on local storage view
3. Click on a patch you downloaded with no patch notes
4. On the right-click "Update Patch Notes"
5. Observe nothing happens

**Expected behavior**
When clicking the Update Patchnotes button I expect the patch notes you could see in PatchStorage view would become available for patches in the local storage view where there are no notes.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional Service Pack 1

**Additional context**
N/A

**Comment by Ch3ryl** [comment]
Oh, this seems to happen to me even with patches downloaded from the app. Weird.

**Comment by meanmedianmoge** [comment]
Update Patch Notes can be used in a number of ways:
1) Load in SD card patch for testing (not on Patchstorage) and include patch information which you can reference and use for operation.
2) Update patch notes for a downloaded patch (from Patchstorage) in case you update things or want more clarity.
3) Copy and paste the Patchstorage patch notes for a new version of downloaded patch that doesn't automatically merge with the PS version.. note that this is a specialized case and is something I aim to address. Right now, it will only merge if the patch names are identical.

Could you explain what you mean by this in some more detail? As I'm not sure which use-case this fits into.
> When clicking the Update Patchnotes button I expect the patch notes you could see in PatchStorage view would become available for patches in the local storage view where there are no notes

**Comment by Ch3ryl** [comment]
I've shared an item with you:

2020-09-10 19-29-59.mp4
https://drive.google.com/file/d/1PjxpgOFbRmpTekwKm6IJWFhPotqZpzJx/view?usp=sharing&invite=CInNhLMC&ts=5f5aecfd

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

Tried sending this via email - too big. Screen capture of what I was  
talking about.

**Comment by meanmedianmoge** [comment]
Thanks for sharing that with me, that was helpful! It seems to be a slight misunderstanding with how the functionality works - Update Patch Notes is what you would click on after you type into or edit the patch notes (Local Storage tab only). The merging that I mentioned above is what happens if you load a patch into the librarian which shares the same name as a patch on PS - the patch notes should appear seamlessly in your custom version of the patch, no additional steps needed!

Can you confirm that the patches you showed have an identical name to their PS counterparts? If they are and the issue still persists after trying a second time (import them again and check the patch notes), I'll investigate this as a bug.

If that is not working, there is another way to get patch notes onto your imported patches. Let's say you have a bunch of previously downloaded patches with edits you've since made. You can simply copy the patch notes from the PS patch, import your version, and paste them into the Local tab panel. Clicking "Update Patch Notes" will save those to the patch metadata.

I hope that helps/makes sense. Thanks again for the screenshare - I'll update the title of this issue to address the merging (allowing for name differences).

**Comment by Ch3ryl** [comment]
Again, sorry for the delay. Yeah, I don't change the Patch names other than
the number when importing into the Zoia. But some of those patches I didn't
even do that. I will try to try again after an import this weekend - this
week was busy for me.
