### ISSUE TITLE
When importing a patch from your SD Card be able to go to it the Local Storage View

### ISSUE THREAD

**Issue by nissane** [meanmedianmoge/zoia_lib#83]
**Is your feature request related to a problem? Please describe.**
I can't always find patches in my sd card that says it's in my local storage.  the sd card view only gives me the file name.  When I try to search for the patch in local storage at times, I don't see it in the results. When I import it I get "that patch exists in your locally saved patches", but I can't find it in local.

I believe this is happening when my sd patch was part of a multi zip file.  so searching for that patch doesn't work

**Describe the solution you'd like**
after I import from the sd card, when I got the message "that patch exists in your locally saved patches", it would be great to have an option to go directly to local storage and see the patch there, so I can reconcile what's in my SD card with what it's called in local storage.

**Describe alternatives you've considered**
have a goto local storage button next to every patch in you sd card where it's already imported.
or
be able to search for patches inside multi patches.

**Additional context**
this is the dialog I am referring to.  After I get it, I have no way to figure out where it's in my local storage, if I can't find it in local storage search results.

<img width="545" alt="Screen Shot 2020-10-04 at 2 05 26 PM" src="https://user-images.githubusercontent.com/1256326/95023373-b80ae380-064a-11eb-936b-7a662141b81b.png">

**Comment by meanmedianmoge** [comment]
This is a deceptively complex problem. The easy case is for single imports, as we could return the patch name and add a button that redirects to that newly imported local patch. For import as multiple patches, we can't really do that, as there's potentially 64 individual choices. The part where it gets really difficult is the import as version history case, which I think is at the core of what you're asking for. This next little aside is something that's been on my mind for a while, and I figure this is a good opportunity to get it down in writing. Feel free to ignore if this doesn't pertain directly to what you're asking.

(Version histories are mostly treated as separate patches, except where the patch name or binary is similar to a patch that already exists as a local patch.. For example, I download Pretty Years from the PS tab and now it exists in my local storage. Let's say I have a folder on my SD with an updated version of PY and I import the folder as a version history. The outcome of this scenario is that the version history will be missing PY, and instead the individual patch gets a new version. This method was chosen so that patches of the same name and id are kept in a consistent place, uniquely identified by a number. That's not to say that I couldn't rename the new PY version to something else entirely so that the version history has its PY patch, but it goes against the uniqueness and merging logic that is built into the librarian. So yeah, deceptively complex.)

As for your alternatives:
I actually think the easier ask is extending the search functionality into those version histories, with the potential caveat that we'd only be able to display the top-level version history name in the search and not the specific version you're looking for (will have to confirm.. this would be a compromise, basically). As for the "go to local storage" button within the SD table - that's a hard no. We have no way of knowing if a certain patch has been imported or not (What if the binary changed? what about the name or position in the SD card?)

To do:
- Add a redirect button for single patch and versioned imports (for both successes and failures)
- Extend search into version history patches
- Investigate how to handle the "deceptively complex" problem I described in the aside

Won't do:
- Anything to deal with multi-import patches (as individuals)
- Button within SD table to tell if importing has occurred

**Comment by nissane** [comment]
Understood.  With the multi import issue, is it possible at least take us to the multi-import match that it's found in?  Or perhaps give us an idea where to look in the dialog that pops up?  Since that pop up occurs, I'm assuming the software knows it's duplicated somewhere. Any hints as to where it is would also help solve this.

Thanks.

**Comment by meanmedianmoge** [comment]
That was my plan: "Add a redirect button for single patch and **versioned imports**". Sorry if that wasn't clear. The only case this pop-up button wouldn't support is the multi import as individual patches. Thanks for the request!

**Comment by meanmedianmoge** [comment]
Slight change of plans // update on this. Redirect buttons are too difficult/cumbersome to navigate between tabs, so hopefully the solution I have works as a compromise. Bonus is that this will support the multi-import as individual patches case, which I mentioned previously as a "won't-do". Here's a brief explanation of what to expect.

- Single imports: If the patch you're attempting to import already exists, the pop-up will list the patch name of what's in Local Storage (if said patch is included in a version history, that name will also be displayed, ie. "megapack 1: subsynth", where megapack 1 is the version history and subsynth is the patch), so you can then easily search for the previously-saved patch.
- Multi imports (bonus!): Same as singles, except it lists the patches which failed to import in one window (far too many windows if we show the pop-up for each individual failed import).
- Version histories: Sample as singles, except it will only display the name of the versioned directory (megapack 1 from our earlier example), which can be searched for / found in Local Storage.

For successful imports, I don't see much benefit in listing off the name of the patch or version history because Local Storage is set up to show the most recent imports / downloads first. A successful import means that the patch or version history will be easily located, no matter what.

_____

Extending the search functionality into version histories is actually trickier than I had initially thought. I have a relatively naive solution in place right now. Basically we have two lists: one for the top level patch data and another for the individual versions inside a history. In the current build, those lists are treated separately (and I intend to keep it that way). However, we can use the search function to combine the results from each list and then remove any overlaps. It has the same limitations as I mentioned before (what is displayed is only the top level patch name, not individual versions), but it works.

For example, let's use our megapack 1 version history again. We want to find the subsynth patch, so we search for "subsynth". The results will include any non-versioned patches with subsynth in their name, category, or tag + any version histories which have subsynth in their versions' name, category, or tag. The caveat is that you won't see the individual subsynth patch until you navigate to the version history which includes it.
