### ISSUE TITLE
Linux package doesn't contain any executable.

### ISSUE THREAD

**Issue by hickscorp** [meanmedianmoge/zoia_lib#85]
Hello,

I've been trying to test the app in two different ways:

- From source, starting it with Python - running `python -m zoia_lib.backend.startup` errors saying that there's no such module.
- From the binary package - but no executable seems to exist for Linux.

Note that running `python3 -m zoia_lib.backend.startup` works on Xubuntu 20.04 after installing `python3-pip`.

**Comment by meanmedianmoge** [comment]
Sorry for the delay on this. I'm actually not super confident on what constitutes as an "executable" for Linux (it's my understanding that technically, every single file is one?), so I went with the approach of allowing users to run it from the command line.

For the latter, running from the binary, you should be able to call something like this. The naming is slightly different for the Linux zip, so that might be why there was some confusion.
```
cd Downloads
./ZOIALibrarian/startup/startup
```

**Comment by meanmedianmoge** [comment]
See the release posted this morning. Sorry this took so long!
