### ISSUE TITLE
No response of the application

### ISSUE THREAD

**Issue by Emptydroid** [meanmedianmoge/zoia_lib#88]
**Describe the bug**
When I try to open the application, nothing happens. It looks like it is active in the dock, but there are no windows for it and if i right click on it I only have force close as an option. When it looks like it is active/launched it says it takes between 70-93% of the processor power.

**To Reproduce**
1. Download the .zip folder
2. Extract the .zip
3. Launch the application

**Expected behavior**
I wanted the application to launch.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Big Sur

**Comment by meanmedianmoge** [comment]
Need to update to Big Sur to test this, but I am a bit wary of losing some plug-ins/driver support. Will do some research on how the new OS has affected others and then dig in.

**Comment by theconsultantde** [comment]
Same issue here. Is there any way I could provide log files to dig into the issue?

Also couldn't make it run by pulling it from GIT, but I assume that's an issue with my python install via brew.

**Comment by meanmedianmoge** [comment]
@theconsultantde log files would be excellent help here. Could you expand on the steps you took to run from source, as well as your versions for brew, Python, and related dependencies? If the problem is occurring during startup, it probably only requires a small tweak to get it running, which would be ideal.

**Comment by theconsultantde** [comment]
Hej!

Sure i'd be happy to help.
Which log files would you need to check? Is there maybe a debug switch for the pre-compiled app?

Regarding the Git install:
I just saw that my OS is not using the python binaries provided by brew per default when checking with which... so I'm not sure whether that maybe was part of my initial issue there. 

However I just did a (non brew-) fresh install of python and followed the git installation instructions. And I got the error "No matching distribution found for pyside2==5.15.0" when trying to install the requirements. However I did install the latest library versions on my own after that. But with the "newest" pyside2 and shiboken2 release (v2-5.15.2) installed accordingly the application did not start correctly. 

However I saw that the error was due to various other missing libraries. After installing the following modules the git version worked just fine: urllib3, bs4, furl, numpi, rarfile. So might be a problem with my newly installed system or just some stuff missing from the requirements.txt.

**Comment by meanmedianmoge** [comment]
Unfortunately there's no debug switch, but I was hoping that there might be something if you ran the application (pre-compiled) from the terminal, with something like this:

```
cd Downloads # or whichever folder you have the app file in
./ZOIALibrarian.app/Contents/MacOS/startup
```

The terminal window should show some sort of error while it tries to boot. That'll give me somewhere to start.

As for the git install, it might be as simple as a broken dependency with the new OS. I use Python 3.8.4, which isn't referenced in the requirements file (but it is mentioned to use at least 3.7 or newer), so that may have something to do with it. In any case, I'm planning to update the pyside2/shiboken2 versions with the v1.1 release, so hopefully that solves the problem.

**Comment by theconsultantde** [comment]
Hi and thanks for the quick response! 👍 

Unfortunately i do not see a file named startup in the MacOS folder...
zsh: no such file or directory: ./ZOIA Librarian.app/Contents/MacOS/startup


When I try to run the 4,2M ZOIA librarian binary directly the same happens as if I'd be running via doubleclick from the apps folder. It starts and the symbol is appearing in the dock, but then the GUI doesn't appear and I also can't access the menu bar on top... with almost 100% CPU usage. Would a process analysis (via activity monitor) or spindump maybe help?

❯ ./ZOIA\ Librarian.app/Contents/MacOS/ZOIA\ Librarian
^C[1]    11238 terminated  ./ZOIA\ Librarian.app/Contents/MacOS/ZOIA\ Librarian

**Comment by meanmedianmoge** [comment]
I appreciate you getting to this quickly! Ah yes, I forgot that I renamed the executable in the bundled releases (from `startup` to `ZOIA Librarian`).

Is that the only thing in the traceback? I would've expected a longer message. Most likely it's within the startup script, because without that the GUI can't load at all. This can either be due to the dependencies, as mentioned, or cause it cannot find the resources necessary... does the splash screen/logo pop up upon running that line?

**Comment by theconsultantde** [comment]
No worries... :-)

Unfortunately nothing else shows up in the terminal until I Control+C the application.
The icon appears in the dock, jumps and then goes to static and then nothing else, no splash screen, no app screen. I could send you the spindump or process analysis... I took a look at it but I couldn't make any sense out of it. 7 MB of text... :)

**Comment by meanmedianmoge** [comment]
No splash screen would indicate that it's not able to find the resources to display it, which was something we ran into earlier but was remedied in a hotfix to the Mac release. Just to confirm, you're using the 54.6mb download from [here](https://github.com/meanmedianmoge/zoia_lib/releases/tag/v1.0) to test?

Feel free to send along both of those; I can take a look and see if there's any useful information within.

**Comment by theconsultantde** [comment]
Yep I am using the version mentioned. Downloaded it yesterday again from that site.

Can I send them to you privately in any way? I'm not sure if there is some information in these files which I do not want to be publicly available. Could send you a gdrive, dropbox, etc. link for example.

**Comment by meanmedianmoge** [comment]
Thanks for confirming. That leads me to believe that will be a simple fix, since I've dealt with this before.

Sure, Dropbox works for me! Would you need my email to send a sharable link?

**Comment by theconsultantde** [comment]
Yeah sure, that would be perfect :)

**Comment by meanmedianmoge** [comment]
Appreciate the share of those. Logs were a bit gibberish to me but I did find this: https://github.com/spesmilo/electrum/issues/6461

Simple fix/workaround seems to involve either downgrading pyside2 to 5.13.1 or upgrading to 5.15.2. My inclination is to upgrade the dependency, as I recall some UI issues with previous versions of pyside2/pyqt5. I will compile an app with this change and submit it to the release page as a hotfix for testing on Big Sur.

**Comment by theconsultantde** [comment]
Okay, perfect - will try it out asap. If I can help in any other way just give me a hint. :)

**Comment by meanmedianmoge** [comment]
@theconsultantde or @Emptydroid can you try using the app file I added [here](https://github.com/meanmedianmoge/zoia_lib/releases/tag/v1.0)? It's the BigSur-Hotfix file. Please let me know if it does not resolve the problem.

**Comment by Emptydroid** [comment]
Hey @meanmedianmoge! Just tried the new app, but still getting the same problem! It I removed every previous Zoia Librarian version before I downloaded the hotfix. Thought I'd attach some activity monitor screenshots if that may help.
![ZOIALibHotfix_Disk](https://user-images.githubusercontent.com/62550797/105475700-f252cc00-5c9f-11eb-8857-279b710b39da.png)
![ZOIALibHotfix_Memory](https://user-images.githubusercontent.com/62550797/105475704-f2eb6280-5c9f-11eb-9377-52f708200fe7.png)
![ZOIALibHotfix_PowerConsumption](https://user-images.githubusercontent.com/62550797/105475705-f2eb6280-5c9f-11eb-94e7-89e0b0ecf1f9.png)
![ZOIALibHotfix_Processor](https://user-images.githubusercontent.com/62550797/105475706-f383f900-5c9f-11eb-9cfb-5e25b32d4b79.png)

**Comment by meanmedianmoge** [comment]
Appreciate the feedback! I'll continue to poke around and try to remedy this for the next release. Apologies for any inconvenience.

**Comment by theconsultantde** [comment]
Hej! The new hotfix works. :-)

Couldn't check in detail, but the app starts now and I'm getting to the GUI.
Will check functionality at the weekend when I'm back from my work trip.

Thanks, awesome & best regards! :-)

**Comment by meanmedianmoge** [comment]
Excellent, I'm glad to hear it! Will close for now, but feel free to reopen if there are any problems.
